#!/bin/sh
#
#	Web page distribution script for rsvndump
#	written by Jonas Gehring <jonas.gehring@boolsoft.org>
#
#	Usage: ./makeweb <root>
#	root is the root directory of the rsvndump source 
#	distribution (trunk)
#

# Some constants
PROG="rsvndump"

# Validate arguments
if [ -z "$1" ]; then 
	echo 
	echo "USAGE: $0 <root>"
	echo 
	exit 1
fi

ROOT="$1"


# Create web page folder and copy static content
mkdir web
cat "${ROOT}/web/index.html"| sed "s/\$DATE/`date +"%B %d, %Y"`/" > web/index.html
cat "${ROOT}/web/news-archive.html"| sed "s/\$DATE/`date +"%B %d, %Y"`/" > web/news-archive.html
cp "${ROOT}/README" web/README
cp "${ROOT}/ChangeLog" web/ChangeLog

# Create dynamic content
rman -f html "${ROOT}/man/${PROG}.1" > web/manpage.html 2> /dev/null

# Scramble email address
for i in web/*;
do
	sed -i 's/jonas\.gehring/$FORENAME\.$SURENAME/g' $i;
done

exit 0
