#!/bin/sh
#
#	e-build generation script for rsvndump
#	written by Jonas Gehring <jonas.gehring@boolsoft.org>
#
#	NOTE: The script should be run as root (or via sudo) and
#	assumes that there is a directory $PROG-$VERSION containing
#	the whole source
#


# Some constants
PROG="rsvndump"
HOMEPAGE="http://saubue.boolsoft.org/projects/rsvndump"
CATEGORY="dev-util"

# Validate arguments
if [ -z "$1" ]; then 
	echo 
	echo "USAGE: $0 <version>"
	echo 
	exit 1
fi

VERSION="$1"


# Add overlay
#echo PORTDIR_OVERLAY="/usr/portage/local/myebuilds" >> /etc/make.conf

# Make ebuild
rm -rf "/usr/portage/local/myebuilds/${CATEGORY}/${PROG}/files"
rm -rf "/usr/portage/local/myebuilds/${CATEGORY}/${PROG}"
mkdir -p "/usr/portage/local/myebuilds/${CATEGORY}/${PROG}/files"
cp "${PROG}.ebuild" "/usr/portage/local/myebuilds/${CATEGORY}/${PROG}/${PROG}-${VERSION}.ebuild"

# Finish ebuild
OLDWD=$PWD
cd "/usr/portage/local/myebuilds/${CATEGORY}/${PROG}"
ebuild "${PROG}-${VERSION}.ebuild" digest
cd "$OLDWD"

exit 0

